### ISSUE TITLE
should we take those values out in the parameter function? or automate their values?

### ISSUE THREAD

**Issue by romain-lopez** [YosefLab/destvi_utils#15]
https://github.com/YosefLab/destvi_utils/blob/0ca056ca11eb2ee3429ad7d46afee631cafe6df3/destvi_utils/_destvi_utils.py#L410

**Comment by cane11** [comment]
With scores there are not so essential anymore as with pvalue. However, we still apply thresholding to significant genes. I don't have a good idea for automatic choice and will take it into parameter.
